languageCode: en-us
baseURL: "/"
title: Akshaya Chanchala
paginate: 5
theme: PaperMod

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Akshaya Chanchala
  description: "Associate SWE @ Infor | CS Grad, 2023"
  keywords: [Blog, Portfolio]
  author: Akshaya Chanchala
  # author: ["Me", "You"] # multiple authors
  #images: ["<link or path of image for opengraph, twitter-cards>"]
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "Hi! I'm Akshaya Chanchala \U0001F44B"
    subtitle: "Associate SWE @ Infor ðŸš€ | CS Grad, 2023 ðŸŽ“"
    # imageUrl: "images/dp.png"
    # imageWidth: 120
    # imageHeight: 120
    # imageTitle: "Data Professor"
    buttons:
      - name: Blogs
        url: blogs
      - name: Projects
        url: projects
      - name: Work
        url: work
      # - name: Design
      #   url: design

  # home-info mode
  homeInfoParams:
    Title: "Welcome! \U0001F44B"
    Content: "CSE Student, 2023 | Web Development Enthusiast | Web3 Beginner | Blogger"

  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/in/akshaya-chanchala/"
    - name: github
      url: "https://github.com/Akshaya101"
    - name: hashnode
      url: "https://akshayachanchala.hashnode.dev/"
    - name: email
      url: "mailto:akshayachanchala1@gmail.com"
    - name: twitter
      url: "https://twitter.com/akshaya_ch_"

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: blog
      name: Blogs
      url: /blogs/
      weight: 4
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 4
    - identifier: work
      name: Work
      url: /work/
      weight: 4
    - identifier: search
      name: Search
      url: /search/
      weight: 4
    - identifier: resume
      name: Resume
      url: "https://drive.google.com/file/d/1IFl8eMVwIZytqJz3rNIUDqyOGyCZdLhr/view?usp=sharing"
      weight: 4

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

